Refine wing

diff --git a/wing b/wing
--- a/wing
+++ b/wing
@@ -1,54 +1,54 @@
 #!/bin/sh
 # WING_URL=
-# _PROT=socks5
-# _USER=
-# _PASS=
-# _HOST=192.168.1.8
-# _PORT=
-# _PATH=
-# _ARGS=
-# _HASH=
+# _PROT=socks5; _USER=; _PASS=; _HOST=192.168.1.8; _PORT=; _PATH=; _ARGS=; _HASH=
 
-[ -z "$SOCKS_PORT" ] && SOCKS_PORT=1080
-
-if [ -f /etc/config/miwifi ]; then # Normal dnsmasq
+if [ -f /etc/openwrt_release ]; then
+	_MODE=ROUTER
+	_OS=OPENWRT
+	_GFW_LIST=/etc
+	#_DNSMASQ_CONF=/tmp/dnsmasq.d
+	_DNSMASQ_CONF=/etc/dnsmasq.conf
+	! grep gfwlist.txt /etc/init.d/dnsmasq > /dev/null && sed -i 's#procd_add_jail_mount /etc/passwd#procd_add_jail_mount /etc/gfwlist.txt /etc/gfwlist.conf /etc/passwd#' /etc/init.d/dnsmasq
+elif [ -f /etc/config/miwifi ]; then
 	_MODE=ROUTER
 	_OS=MIWIFI
-	_GFWLIST_CONF=/data/wing/gfwlist.conf
-	_GFWLIST_URL=https://cokebar.github.io/gfwlist2dnsmasq/dnsmasq_gfwlist_ipset.conf
+	_GFW_LIST=/data/wing
+	_DNSMASQ_CONF=/tmp/dnsmasq.d
 	PATH=/data/wing:$PATH
-	export LD_LIBRARY_PATH=/data/wing
-elif [ -d /etc/storage ]; then # Yonsm's dnsmasq with gfwlist and tcpdns
+	export LD_LIBRARY_PATH=/data/wing:$LD_LIBRARY_PATH
+elif [ -d /etc/storage ]; then
 	_MODE=ROUTER
 	_OS=PADAVAN
-	DNSMASQ_CONF=/etc/storage/dnsmasq/dnsmasq.conf
-	_GFWLIST_CONF=/etc/storage/dnsmasq/gfwlist.txt
-	_GFWLIST_CONF_RO=/etc_ro/gfwlist.txt
-	_GFWLIST_URL=https://cokebar.github.io/gfwlist2dnsmasq/gfwlist_domain.txt
+	_GFW_LIST=/etc/storage/dnsmasq
+	_GFW_LIST_RO=/etc_ro/gfwlist.txt
+	_DNSMASQ_CONF=/etc/storage/dnsmasq/dnsmasq.conf
 else
-	_MODE=OTHER
+	_MODE=SERVICE
 	if type networksetup >/dev/null 2>&1; then
 		[ -z "$WING_PAC" ] && WING_PAC=1
 		_OS=MACOS
-		_GFWLIST_CONF=/Library/WebServer/Documents/gfwlist.pac
-		_GFWLIST_URL=https://raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac
-		[ ! -f $_GFWLIST_CONF ] && sudo chmod 777 /Library/WebServer/Documents
+		_GFW_LIST=/Library/WebServer/Documents/gfwlist.pac
+		[ ! -f $_GFW_LIST ] && sudo chmod 777 /Library/WebServer/Documents
 	else
-		_OS=OTHER
+		_OS=LINUX
+		_GFW_LIST=./gfwlist.pac
 	fi
-	
 fi
 
-log()
-{
+if [ $_MODE = ROUTER ]; then
+	[ ! -d $_DNSMASQ_CONF ] && dnsmasq --help | grep gfwlist >/dev/null 2>&1 && _GFW_LIST=$_GFW_LIST/gfwlist.txt || _GFW_LIST=$_GFW_LIST/gfwlist.conf
+fi
+
+log() {
 	case "$1" in
 		0|1) echo "$2";;
 		2|3) echo "$2" >> /tmp/wing.log;;
 	esac
 }
 
-usage()
-{
+log $1 "Wing to World on $OS in $_MODE mode"
+
+usage() {
 	echo "Usage: $0 <[start]|stop|restart|pause|resume|update|install|status|-s 2/t/s/y/*|-h>"
 	echo
 	echo "$0 [-v[0-5]] <URL>"
@@ -58,40 +58,27 @@ usage()
 	exit 1
 }
 
-update()
-{
-	[ ! -z "$3" ] && _GFWLIST_CONF="$3"
-	curl --socks5-hostname $1:$2 -k -o $_GFWLIST_CONF $_GFWLIST_URL || exit 1
+update() {
+	[ ! -z "$1" ] && _GFW_LIST="$1"
+	_FMT=${_GFW_LIST##*.}
+	[ "$_FMT" = conf -o "$_FMT" = pac ] && _GFW_TMP=/tmp/gfwlist.txt || _GFW_TMP=$_GFW_LIST
 
-	if [ $_OS = PADAVAN ]; then
-		cat << EOF >> $_GFWLIST_CONF
-pypi.org
-pythonhosted.org
-openwrt.org
-facebook-hardware.com
-fbthirdpartypixel.com
-workplace.com
-EOF
-	elif [ $_OS = MIWIFI ]; then
-		cat << EOF >> $_GFWLIST_CONF
-server=/pypi.org/127.0.0.1#5353
-ipset=/pypi.org/gfwlist
-server=/pythonhosted.org/127.0.0.1#5353
-ipset=/pythonhosted.org/gfwlist
-server=/openwrt.org>/127.0.0.1#5353
-ipset=/openwrt.org/gfwlist
-server=/facebook-hardware.com/127.0.0.1#5353
-ipset=/facebook-hardware.com/gfwlist
-server=/fbthirdpartypixel.com/127.0.0.1#5353
-ipset=/fbthirdpartypixel.com/gfwlist
-server=/workplace.com/127.0.0.1#5353
-ipset=/workplace.com/gfwlist
-EOF
+	curl -k -o $_GFW_TMP https://raw.githubusercontent.com/Yonsm/OponWrt/main/fix-files/package/helloworld/wing/gfwlist.txt || (echo "githubusercontent.com" > $_GFW_TMP; echo "Update gfwlist failed! You should run wing update again.")
+	if [ $_FMT = conf ]; then
+		sed -e 's_^_server=/_' -e 's_$_/127.0.0.1#5354_' $_GFW_TMP > $_GFW_LIST
+		sed -e 's_^_ipset=/_' -e 's_$_/gfwlist_' $_GFW_TMP >> $_GFW_LIST
+	elif [ $_FMT = pac ]; then
+		echo "var s = [" > $_GFW_LIST
+		sed -e 's/^/"/' -e 's/$/",/' $_GFW_TMP >> $_GFW_LIST
+		[ -z $2 ] && _IP=127.0.0.1 || _IP=$2
+		echo "]; function FindProxyForURL(u, h) { for (var i = 0; i < s.length; i++) { var r = s[i]; if (h == r || h.endsWith('.' + r)) return 'SOCKS5 $_IP:1080; DIRECT'; } return 'DIRECT'; }" >> $_GFW_LIST
+	else
+		return
 	fi
+	rm $_GFW_TMP
 }
 
-split_str()
-{
+split_str() {
 	case "$4" in
 	"")
 		export $1=
@@ -108,8 +95,7 @@ split_str()
 	esac
 }
 
-rsplit_str()
-{
+rsplit_str() {
 	case "$4" in
 	"")
 		export $1=
@@ -126,8 +112,7 @@ rsplit_str()
 	esac
 }
 
-parse_query()
-{
+parse_query() {
 	local IFS_BAK=$IFS
 	IFS=\&
 	for ITEM in $1; do
@@ -138,28 +123,25 @@ parse_query()
 	IFS=$IFS_BAK
 }
 
-parse_uri()
-{
-	split_str _TEXT _HASH \# $1
-	split_str _SERV_PATH _ARGS ? $_TEXT
-	parse_query $_ARGS
-	split_str _SERV _PATH / $_SERV_PATH
-	rsplit_str _USER_PASS _HOST_PORT @ $_SERV
-	split_str  _USER _PASS : $_USER_PASS
-	split_str _HOST _PORT : $_HOST_PORT
+parse_uri() {
+	split_str "_TEXT" _HASH \# $1
+	split_str _SERV_PATH _ARGS \? "$_TEXT"
+	parse_query "$_ARGS"
+	split_str _SERV _PATH / "$_SERV_PATH"
+	rsplit_str _USER_PASS _HOST_PORT @ "$_SERV"
+	split_str  _USER _PASS : "$_USER_PASS"
+	split_str _HOST _PORT : "$_HOST_PORT"
 }
 
-parse_url()
-{
+parse_url() {
 	split_str _PROT _TEXT : "$1" R
 	case "$_TEXT" in
-		//*) _TEXT=${_TEXT:2}
+		//*) _TEXT="${_TEXT:2}"
 	esac
-	parse_uri $_TEXT
+	parse_uri "$_TEXT"
 }
 
-make_url()
-{
+make_url() {
 	local URL="$_PROT://$_USER"
 	[ "$_PASS" ] && URL="$URL:$_PASS"
 	URL="$URL@$_HOST:$_PORT"
@@ -169,8 +151,7 @@ make_url()
 	echo $URL
 }
 
-decode_b64()
-{
+decode_b64() {
 	local CNT=${#1}
 	local REM=$(( $CNT % 4 ))
 	if [ $REM -eq 1 ]; then
@@ -185,23 +166,20 @@ decode_b64()
 	echo $TEXT | base64 -d
 }
 
-prepare()
-{
+prepare() {
 	[ $_OS = MACOS ] && [ "$WING_PAC" != "1" ] && return
 
-	if [ ! -f $_GFWLIST_CONF ]; then
-		if [ ! -z $_GFWLIST_CONF_RO ] && [ -f $_GFWLIST_CONF_RO ]; then
-			_GFWLIST_CONF=$_GFWLIST_CONF_RO
+	if [ ! -f $_GFW_LIST ]; then
+		if [ ! -z $_GFW_LIST_RO ] && [ -f $_GFW_LIST_RO ]; then
+			_GFW_LIST=$_GFW_LIST_RO
 		else
-			sleep 2
-			update $1 $2
+			update
 		fi
 		[ $_OS = MACOS ] && [ "$WING_PAC" = "1" ] && sudo apachectl restart
 	fi
 }
 
-inject()
-{
+inject() {
 	if [ $_MODE = ROUTER ]; then
 		iptables -t nat $1 OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1088
 		iptables -t nat $1 PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1088
@@ -230,9 +208,8 @@ inject()
 				networksetup -setsocksfirewallproxystate "$WING_NETWORK" on
 			return 0
 		elif [ $1 == -D ]; then
-			[ "$WING_PAC" = "1" ] && 
-				networksetup -setautoproxystate "$WING_NETWORK" off || 
-				networksetup -setsocksfirewallproxystate "$WING_NETWORK" off
+			networksetup -setautoproxystate "$WING_NETWORK" off
+			networksetup -setsocksfirewallproxystate "$WING_NETWORK" off
 		else
 			echo "Local Network: $WING_NETWORK"
 			echo "export ALL_PROXY=socks5://$2:$3"
@@ -243,9 +220,8 @@ inject()
 	fi
 }
 
-proxy()
-{
-	prepare $3 $4
+proxy() {
+	prepare
 
 	if [ $_MODE = ROUTER ]; then
 		ulimit -n 65536
@@ -278,38 +254,43 @@ proxy()
 		#ipset add gfwlist 109.239.140.0/24
 		#ipset add gfwlist 149.154.160.0/20
 
+		# dns2tcp
+		if type dns2tcp>/dev/null 2>&1; then
+			dns2tcp -L 0.0.0.0#5354 -R 8.8.8.8#53 &
+		else
+			dns-forwarder -p 5354 &
+		fi
+
 		# dnsmasq
-		if [ $_OS = PADAVAN ]; then
-			GFWLIST_LINE="gfwlist=$_GFWLIST_CONF"
-			if ! grep "$GFWLIST_LINE" $_DNSMASQ_CONF > /dev/null; then
-				killall dnsmasq
-				echo "$GFWLIST_LINE" >> $_DNSMASQ_CONF
-				dnsmasq
+		if [ -d $_DNSMASQ_CONF ]; then
+			if [ ! -f $_DNSMASQ_CONF/${_GFW_LIST##*/} ]; then
+				[ $_OS = OPENWRT ] && cp $_GFW_LIST $_DNSMASQ_CONF || ln -s $_GFW_LIST $_DNSMASQ_CONF
+				/etc/init.d/dnsmasq restart
 			fi
 		else
-			dns-forwarder -p 5353 &
-			ln -s $_GFWLIST_CONF /tmp/dnsmasq.d/
-			/etc/init.d/dnsmasq restart
+			[ ${_GFW_LIST##*.} = txt ] && GFWLIST_LINE="gfwlist=$_GFW_LIST" || GFWLIST_LINE="conf-file=$_GFW_LIST"
+			if ! grep "$GFWLIST_LINE" $_DNSMASQ_CONF > /dev/null; then
+				echo "$GFWLIST_LINE" >> $_DNSMASQ_CONF
+				[ $_OS = PADAVAN ] && (killall dnsmasq; dnsmasq) || /etc/init.d/dnsmasq restart
+			fi
 		fi
 	fi
 
 	inject -A $3 $4
 }
 
-resolve()
-{
+resolve() {
 	[ $_OS = MACOS ] && return
 
 	CNT=0
-	while [ $CNT -le 20 ]
-	do
+	while [ $CNT -le 20 ]; do
 		local IP=`nslookup $_HOST | awk -F": " '/^Address/ {if (NR>4){print $2;exit 1}}' | cut -d' ' -f 1`
 		log $1 "Resolve $_HOST=>$IP"
 		case "$IP" in
 		192.168.*|127.0.*|"")
 			;;
 		*)
-			_HOST=$IP
+			#_HOST=$IP
 			return
 			;;
 		esac
@@ -318,8 +299,7 @@ resolve()
 	done
 }
 
-ssxcmd()
-{
+ssxcmd() {
 	resolve $1
 	[ -z $_PORT ] && _PORT=443
 	if [ $RUN_MODE = ROUTER-redir ]; then
@@ -327,9 +307,9 @@ ssxcmd()
 		local LOCAL_PORT=1088
 	else
 		local RUN_TYPE=local
-		local LOCAL_PORT=$SOCKS_PORT
+		local LOCAL_PORT=1080
 		if type ssr-client >/dev/null 2>&1; then
-			echo "{\"password\":\"${_PASS//%/\\x}\",\"method\":\"$_USER\",\"protocol\":\"$_PATH\",\"protocol_param\":\"$_protoparam\",\"obfs\":\"$_HASH\",\"obfs_param\":\"$_obfsparam\",\"client_settings\":{\"server\":\"$_HOST\",\"server_port\":$_PORT,\"listen_address\":\"0.0.0.0\",\"listen_port\":$SOCKS_PORT}}" > /tmp/ssr.conf
+			echo "{\"password\":\"${_PASS//%/\\x}\",\"method\":\"$_USER\",\"protocol\":\"$_PATH\",\"protocol_param\":\"$_protoparam\",\"obfs\":\"$_HASH\",\"obfs_param\":\"$_obfsparam\",\"client_settings\":{\"server\":\"$_HOST\",\"server_port\":$_PORT,\"listen_address\":\"0.0.0.0\",\"listen_port\":$LOCAL_PORT}}" > /tmp/ssr.conf
 			XCMD="ssr-client -c /tmp/ssr.conf"
 			return
 		fi
@@ -338,9 +318,8 @@ ssxcmd()
 	XCMD="$2-$RUN_TYPE -s $_HOST -p $_PORT -k ${_PASS//%/\\x} -b 0.0.0.0 -l $LOCAL_PORT -m $_USER $3"
 }
 
-start()
-{
-	if [ ! -z $2 ]; then
+start() {
+	if [ ! -z "$2" ]; then
 		parse_url $2
 	elif [ -z $_PROT ]; then
 		[ -z $WING_URL ] && usage
@@ -359,9 +338,9 @@ start()
 			local LOCAL_PORT=1088
 		else
 			local RUN_TYPE=client
-			local LOCAL_PORT=$SOCKS_PORT
+			local LOCAL_PORT=1080
 		fi
-		resolve $1
+		#resolve $1
 		[ -z $_PORT ] && _PORT=443
 		echo "{\"run_type\":\"$RUN_TYPE\",\"local_addr\":\"0.0.0.0\",\"local_port\":$LOCAL_PORT,\"remote_addr\":\"$_HOST\",\"remote_port\":$_PORT,\"password\":[\"${_USER//%/\\x}\"],\"log_level\":$1,\"ssl\":{\"verify\":false}}" > /tmp/trojan.conf
 		XCMD="trojan -c /tmp/trojan.conf"
@@ -390,7 +369,7 @@ start()
 		ssxcmd $1 ss
 		;;
 	socks5)
-		[ -z $_PORT ] && _PORT=$SOCKS_PORT
+		[ -z $_PORT ] && _PORT=1080
 		proxy $1 $_PROT $_HOST $_PORT
 		return
 		;;
@@ -400,71 +379,68 @@ start()
 		;;
 	esac
 
-	if [ $1 -ge 2 ] && [ $1 -le 3 ]; then
+	proxy $1 $_PROT 127.0.0.1 1080
+
+	if [ $1 -ge 4 ]; then
+		$XCMD &
+	elif [ $1 -ge 2 ]; then
 		nohup "$XCMD" &> /tmp/wing.log &
 	else
-		$XCMD &
-	fi
-
-	proxy $1 $_PROT 127.0.0.1 $SOCKS_PORT
-
-	if [ $1 -le 1 ] && [ $_MODE != ROUTER ]; then
 		echo
 		echo "export WING_URL=\"`make_url`\""
 		echo
-		echo "Press Enter to exit"
+		echo "$XCMD"
 		echo
-		read
+		$XCMD
 		stop
-		sleep 1
 	fi
 }
 
-stop()
-{
+stop() {
 	inject -D 2> /dev/null
 
-	killall trojan ssr-local ssr-redir ss-local ss-redir ssr-client ipt2socks dns-forwarder 2> /dev/null
+	killall trojan ssr-local ssr-redir ss-local ss-redir ssr-client ipt2socks dns2tcp dns-forwarder 2> /dev/null
 	rm /tmp/trojan.conf /tmp/ssr.conf /tmp/wing.log /tmp/ipt2socks.log 2> /dev/null
 
 	if [ $_MODE = ROUTER ]; then
 		ipset flush gfwlist
 		ipset destroy gfwlist
 		[ "$1" == "-R" ] && return
-		if [ $_OS = PADAVAN ]; then
-			prepare
-			sed -i /gfwlist=${_GFWLIST_CONF//\//\\/}/d $_DNSMASQ_CONF
-			killall dnsmasq
-			dnsmasq
+
+		prepare
+
+		if [ -d $_DNSMASQ_CONF ]; then
+			rm $_DNSMASQ_CONF/${_GFW_LIST##*/} && /etc/init.d/dnsmasq restart
 		else
-			rm /tmp/dnsmasq.d/gfwlist.conf
-			/etc/init.d/dnsmasq restart
+			[ ${_GFW_LIST##*.} = txt ] && GFWLIST_LINE="gfwlist=$_GFW_LIST" || GFWLIST_LINE="conf-file=$_GFW_LIST"
+			if grep "$GFWLIST_LINE" $_DNSMASQ_CONF > /dev/null; then
+				sed -i /${GFWLIST_LINE//\//\\/}/d $_DNSMASQ_CONF
+				[ $_OS = PADAVAN ] && (killall dnsmasq; dnsmasq) || /etc/init.d/dnsmasq restart
+			fi
 		fi
 	fi
 
 	echo Wing service stopped
 }
 
-install()
-{
+install() {
 	if [ $_OS = MIWIFI ]; then
 		uci set firewall.wing=include
 		uci set firewall.wing.type="script"
-		uci set firewall.wing.path="/data/wing/wing $2"
+		uci set firewall.wing.path="/data/wing/wing restart $1"
 		uci set firewall.wing.enabled="1"
 		uci commit firewall
 		uci show firewall.wing
-	elif [ $_OS = MACOS ]; then
+	else
 		echo TODO
 	fi
 }
 
-status()
-{
+status() {
 	case "$1" in
 	2) tail -f /tmp/ipt2socks.log;;
 	t) iptables -t nat -L PREROUTING && iptables -t nat -L OUTPUT;;
-	s) ipset -L gfwlist | more;;
+	s) ipset -L gfwlist;;
 	y) tail -f /tmp/syslog.log;;
 	*) tail -f /tmp/wing.log;;
 	esac
@@ -492,7 +468,7 @@ resume)
 	inject -C || inject -A
 	;;
 update)
-	update 127.0.0.1 $SOCKS_PORT "$2"
+	update "$2" "$3"
 	;;
 install)
 	install "$2"
